// Generated by scripts/generate-keytao-flykey-practice.mjs. Do not edit by hand.

export const KEYTAO_FLY_KEY_SOURCE = {
  "source": "xkinput/Rime_JD:rime/keytao.single.dict.yaml",
  "sourceVersion": "2026.05.09",
  "commonSource": "Jun Da Modern Chinese Character Frequency List",
  "limit": 500,
  "commonScanLimit": 10000,
  "totalEntries": 17721,
  "totalCharacters": 500
} as const

export const KEYTAO_FLY_KEY_CHARACTERS = "这中出着之种成主只者长知正重战政产制常真处场直指至治展光住程张术传识争持车证转准单调质城整况支照称查除找装广吃专周注众致陈责章志站终黄察织双朝止值助属船职状创承初置充洲冲州差占征沉超皇执追著穿阵楚智掌钟春招逐择厂炸抓镇础纸诸庄齐床窗震川针哲朱植纯筑折郑臣振盛狂诚丁赵抽桌触召侧债乘障彻丈唱症撤茶珠虫驻潮珍忠荒偿迟净矿晨吹诊扎抢宙壮殖尺侦崇枝插氏储仇撞呈竹垂帐昌尝涌慌祝赤筹沈旨柱仲池仗尘秩猪齿祭肿晃涨惩捉串缴址斥宅挣唇颤丑肠卓皱睁填喘罩柴酬摘畜吵骤缠翅拆胀扯驰臭趁愁倘浙畅闯厨遮圳框芝嘱衷耻账赚撑倡昭怔蠢禅阐脂谎抄舟痴叉拓粘窄兆刹煌坠咒巢撰滞寨辰惶嘲肢砖蒸爪贞眨爽沾诈斋宠杖轴凰椎斩匙沼株桩衬铸詹恍烛汁醇幢煮炒敞蜡枕掷霜剿绸妆逛钞昼蛛侄诏畴拙稚诧旷拯澄瞅盏吱帜贮咋冢裳屯灼乍琢绰锤戳彰瞻酌浊淌栅缀肘挚粥矗揣崭橱蜘峙蝉朕铲锥侈疮绽岔淳铮趾嫦斟逞忏叱湛眶栈渣肇辙札疹窒幌拽嗤匡璋轧蝗诛炽闸臻踌掺沌喳瞩躇忡忱炊钊丞弛琛澈稠簧搀猖怅筐敕筝竺啄毡捶雏辗锄嗔磺辄帧橙赘娼铢掣嚓憧帚钗哧喋榨炙侏搐踵挝惴桢秤饬痔褶茬漳褚祯馋胱镯翟甄蟾蘸蔗淖婵蛀盅啜瞠谆骋潺狰辍樟伫惆徵怆槌蚣赈谌徨痣谄黜蛰璜咫椿锺祗拄豺啻篆蛭郅胄蟑箴" as const
