const RIME_USER_DIR = '/rime'
const RIME_SHARED_DIR = '/usr/share/rime-data'
const OPENCC_DIR = '/usr/share/opencc'

let rimeModule = null
let manifest = null
let schemas = []
let deployResolver = null

function ok(id, result) {
  self.postMessage({ id, ok: true, result })
}

function formatError(error) {
  if (error instanceof Error) return error.message
  if (typeof error === 'string') return error
  if (error && typeof error === 'object') {
    const details = [error.name, error.message, error.stack].filter(Boolean).join(': ')
    if (details) return details

    try {
      return JSON.stringify(error)
    } catch {
      return Object.prototype.toString.call(error)
    }
  }

  return String(error)
}

function fail(id, error) {
  self.postMessage({
    id,
    ok: false,
    error: formatError(error),
  })
}

function status(message, detail, progress) {
  self.postMessage({
    type: 'status',
    status: { message, detail, progress },
  })
}

function ensureModule() {
  if (!rimeModule) throw new Error('librime wasm module is not initialized')
  return rimeModule
}

function call(name, returnType, argTypes = [], args = []) {
  return ensureModule().ccall(name, returnType, argTypes, args)
}

function isFileExistsError(error) {
  return error?.errno === 20 || error?.code === 'EEXIST' || String(error).includes('File exists')
}

function mkdirp(path) {
  const fs = ensureModule().FS
  const parts = path.split('/').filter(Boolean)
  let current = ''

  for (const part of parts) {
    current += `/${part}`
    try {
      fs.mkdir(current)
    } catch (error) {
      if (!isFileExistsError(error)) throw error
    }
  }
}

function parentDir(path) {
  const index = path.lastIndexOf('/')
  return index <= 0 ? '/' : path.slice(0, index)
}

function targetPathForDeployFile(path) {
  const normalizedPath = path.replace(/^\/+/, '')
  if (normalizedPath.startsWith('opencc/')) return `${OPENCC_DIR}/${normalizedPath.slice('opencc/'.length)}`
  if (normalizedPath.startsWith('rime-data/')) return `${RIME_SHARED_DIR}/${normalizedPath.slice('rime-data/'.length)}`
  return `${RIME_USER_DIR}/${normalizedPath}`
}

function writeDeployFile(file) {
  const targetPath = targetPathForDeployFile(file.path)
  mkdirp(parentDir(targetPath))
  ensureModule().FS.writeFile(targetPath, new Uint8Array(file.content))
}

function stripYamlScalar(value) {
  return value.trim().replace(/^['"]|['"]$/g, '')
}

function readYamlScalar(content, key) {
  const match = content.match(new RegExp(`^\\s*${key}:\\s*([^\\n#]+)`, 'm'))
  return match ? stripYamlScalar(match[1]) : null
}

function readSchemaMetadata(content) {
  const schemaBlock = content.match(/^schema:\s*\n((?:[ \t]+[^\n]*\n?)*)/m)?.[1] ?? ''

  return {
    id: readYamlScalar(schemaBlock, 'schema_id') ?? readYamlScalar(content, 'schema_id'),
    name: readYamlScalar(schemaBlock, 'name') ?? readYamlScalar(content, 'name'),
  }
}

function decodeDeployFile(file) {
  return new TextDecoder('utf-8').decode(new Uint8Array(file.content))
}

function inferSchemasFromDeployFiles(files) {
  const schemasById = new Map()
  const orderedSchemaIds = []

  for (const file of files ?? []) {
    if (!file.path.endsWith('.schema.yaml')) continue

    const content = decodeDeployFile(file)
    const metadata = readSchemaMetadata(content)
    const id = metadata.id ?? file.path.split('/').pop()?.replace(/\.schema\.yaml$/, '')
    if (!id) continue

    const name = metadata.name ?? id
    const existing = schemasById.get(id)
    if (existing && existing.name !== existing.id && name === id) continue

    schemasById.set(id, {
      id,
      name,
    })
  }

  for (const file of files ?? []) {
    if (!file.path.endsWith('default.custom.yaml') && !file.path.endsWith('default.yaml')) continue

    const content = decodeDeployFile(file)
    for (const match of content.matchAll(/^\s*-\s*schema:\s*([^\n#]+)/gm)) {
      const id = stripYamlScalar(match[1])
      if (id && !orderedSchemaIds.includes(id)) orderedSchemaIds.push(id)
    }
  }

  const orderedSchemas = orderedSchemaIds
    .map((id) => schemasById.get(id) ?? { id, name: id })
  const remainingSchemas = [...schemasById.values()]
    .filter((schema) => !orderedSchemaIds.includes(schema.id))

  return orderedSchemas.length > 0 ? orderedSchemas : remainingSchemas
}

function writeDefaultSchemaList(schemaList) {
  if (schemaList.length === 0) return

  mkdirp(`${RIME_USER_DIR}/build`)
  const content = [
    '# generated by KeyTao practice',
    'schema_list:',
    ...schemaList.map((schema) => `  - schema: ${schema.id}`),
    'menu:',
    '  page_size: 6',
    'recognizer:',
    '  patterns:',
    '    uppercase: "[A-Z][-_+\\\'.0-9A-Za-z]*$"',
    '    url: "^(www[.]|https?:|ftp:|mailto:).*$"',
    'key_binder:',
    '  bindings:',
    '    - { when: composing, accept: Control+p, send: Up }',
    '    - { when: composing, accept: Control+n, send: Down }',
    '    - { when: has_menu, accept: minus, send: Page_Up }',
    '    - { when: has_menu, accept: equal, send: Page_Down }',
    '',
  ].join('\n')
  ensureModule().FS.writeFile(`${RIME_USER_DIR}/build/default.yaml`, content)
}

function syncfs(populate) {
  const fs = ensureModule().FS
  if (!fs.syncfs) return Promise.resolve()

  return new Promise((resolve, reject) => {
    fs.syncfs(populate, (error) => {
      if (error) reject(error)
      else resolve()
    })
  })
}

function normalizeResult(result) {
  if (!result || typeof result !== 'object') {
    return { accepted: false, composition: null }
  }

  const composition = result.state === 1
    ? {
        preedit: `${result.head ?? ''}${result.body ?? ''}${result.tail ?? ''}`,
        candidates: Array.isArray(result.candidates)
          ? result.candidates.map((candidate, index) => ({
              text: candidate.text,
              comment: candidate.comment,
              label: result.selectLabels?.[index],
            }))
          : [],
        highlightedIndex: result.highlighted ?? 0,
        page: result.page ?? 0,
        isLastPage: Boolean(result.isLastPage),
      }
    : null

  return {
    accepted: result.state === 0 || result.state === 1,
    committedText: result.committed,
    composition,
  }
}

function parseRimeJson(json) {
  return normalizeResult(JSON.parse(json || '{}'))
}

function parseDataDownloadProgress(message) {
  const match = String(message).match(/\((\d+)\/(\d+)\)/)
  if (!match) return null

  const loaded = Number(match[1])
  const total = Number(match[2])
  if (!Number.isFinite(loaded) || !Number.isFinite(total) || total <= 0) return null
  return Math.min(55, 35 + Math.round((loaded / total) * 20))
}

function createModuleOptions() {
  return {
    locateFile(file) {
      return `${manifest.basePath}/${file}`
    },
    setStatus(message) {
      const downloadProgress = parseDataDownloadProgress(message)
      if (downloadProgress !== null) {
        status('正在加载浏览器 librime 数据包', message, downloadProgress)
        return
      }

      if (message) status('正在启动浏览器 librime', message, 55)
    },
    monitorRunDependencies(count) {
      if (count > 0) status('正在装载 librime wasm 运行依赖', `剩余 ${count} 项`, 45)
    },
    onAbort(message) {
      status('librime wasm 启动中止', String(message || '未知错误'), 100)
    },
    printErr(message) {
      if (!String(message).includes('I202')) console.warn(message)
    },
  }
}

async function loadRimeModule() {
  status('正在加载浏览器 librime', '下载 worker 运行时脚本', 30)

  const moduleOptions = createModuleOptions()
  self.Module = moduleOptions
  importScripts(manifest.rimeJs ?? 'rime.js')

  const factory = self.createRimeModule ?? self.RimeModule
  if (typeof factory === 'function') {
    status('正在实例化 librime wasm', '调用 Emscripten module factory', 40)
    return await factory({ ...moduleOptions, noInitialRun: true })
  }

  if (self.Module && typeof self.Module.ccall === 'function') {
    if (self.Module.calledRun) return self.Module

    status('正在等待 librime wasm runtime ready', '初始化 Emscripten Module', 55)
    return await new Promise((resolve, reject) => {
      const timeout = self.setTimeout(() => reject(new Error('Timed out waiting for rime.js runtime initialization')), 45000)
      self.Module.onRuntimeInitialized = () => {
        self.clearTimeout(timeout)
        resolve(self.Module)
      }
      self.Module.onAbort = (message) => {
        self.clearTimeout(timeout)
        reject(new Error(String(message || 'librime wasm runtime aborted')))
      }
    })
  }

  throw new Error('rime.js did not expose a compatible Emscripten Module')
}

async function init(payload) {
  if (rimeModule) return

  manifest = payload.manifest
  schemas = manifest.schemas ?? []

  self._deployStatus = (status, schemaJson) => {
    if (status === 'success') {
      try {
        schemas = JSON.parse(schemaJson)
      } catch {
        schemas = []
      }
    }

    deployResolver?.(status)
    deployResolver = null
  }

  rimeModule = await loadRimeModule()
  status('正在初始化 librime 文件系统', '挂载 /rime 和共享数据目录', 58)

  mkdirp(RIME_USER_DIR)
  mkdirp(RIME_SHARED_DIR)
  mkdirp(OPENCC_DIR)

  const fs = rimeModule.FS
  if (fs.filesystems?.IDBFS) {
    try {
      fs.mount(fs.filesystems.IDBFS, {}, RIME_USER_DIR)
      await syncfs(true)
    } catch (error) {
      console.warn(error)
    }
  }

  status('正在调用 librime init', '初始化输入引擎', 60)
  call('init', 'null')
  call('set_page_size', 'null', ['number'], [10])
}

async function deploy(payload) {
  for (const file of payload.files ?? []) writeDeployFile(file)
  schemas = inferSchemasFromDeployFiles(payload.files ?? [])
  writeDefaultSchemaList(schemas)
  await syncfs(false)

  const deployment = new Promise((resolve) => {
    deployResolver = resolve
    self.setTimeout(() => resolve('timeout'), 45000)
  })

  call('deploy', 'null')
  const status = await deployment
  await syncfs(false)
  if (status === 'failure') throw new Error('librime deployment failed')
  if (schemas.length === 0) schemas = inferSchemasFromDeployFiles(payload.files ?? [])
}

async function selectSchema(payload) {
  call('set_ime', 'null', ['string'], [payload.schemaId])
  call('set_option', 'null', ['string', 'number'], ['ascii_mode', 0])
  await syncfs(false)
  return { accepted: false, composition: null }
}

async function processKey(payload) {
  const result = parseRimeJson(call('process', 'string', ['string'], [payload.key]))
  if (result.committedText) await syncfs(false)
  return result
}

async function selectCandidate(payload) {
  const result = parseRimeJson(call('select_candidate_on_current_page', 'string', ['number'], [payload.index]))
  if (result.committedText) await syncfs(false)
  return result
}

async function changePage(payload) {
  return parseRimeJson(call('change_page', 'string', ['boolean'], [payload.backward]))
}

async function reset() {
  if (!rimeModule) return
  call('reset', 'null')
  await syncfs(false)
}

const handlers = {
  init,
  deploy,
  listSchemas: async () => schemas,
  selectSchema,
  processKey,
  selectCandidate,
  changePage,
  reset,
}

self.onmessage = async (event) => {
  const { id, type, payload } = event.data
  const handler = handlers[type]

  if (!handler) {
    fail(id, `Unknown librime wasm worker request: ${type}`)
    return
  }

  try {
    ok(id, await handler(payload ?? {}))
  } catch (error) {
    fail(id, error)
  }
}